<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="OrangeHRM" duration-ms="5119" started-at="2020-02-21T10:16:33Z" finished-at="2020-02-21T10:16:38Z">
    <groups>
      <group name="LoginGroup">
        <method signature="LoginTests.TC1VerifyValidAdminUser(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.orangehrm.tests.LoginTests@12050f6]" name="TC1VerifyValidAdminUser" class="com.orangehrm.tests.LoginTests"/>
      </group> <!-- LoginGroup -->
    </groups>
    <test name="OrangeHRM test" duration-ms="5119" started-at="2020-02-21T10:16:33Z" finished-at="2020-02-21T10:16:38Z">
      <class name="com.orangehrm.tests.LoginTests">
        <test-method status="FAIL" signature="TC1VerifyValidAdminUser(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.orangehrm.tests.LoginTests@12050f6]" name="TC1VerifyValidAdminUser" duration-ms="5090" started-at="2020-02-21T10:16:33Z" data-provider="excelData" finished-at="2020-02-21T10:16:38Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[java.util.concurrent.ExecutionException: java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at org.testng.internal.PoolService.submitTasksAndWait(PoolService.java:53)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:970)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.testng.internal.PoolService.submitTasksAndWait(PoolService.java:51)
... 6 more
Caused by: java.lang.NullPointerException
at com.orangehrm.common.ImplIinvokedListner.afterInvocation(ImplIinvokedListner.java:44)
at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:493)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:617)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1VerifyValidAdminUser -->
        <test-method status="PASS" signature="afterSuit()[pri:0, instance:com.orangehrm.tests.LoginTests@12050f6]" name="afterSuit" is-config="true" duration-ms="4" started-at="2020-02-21T10:16:39Z" finished-at="2020-02-21T10:16:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuit -->
      </class> <!-- com.orangehrm.tests.LoginTests -->
    </test> <!-- OrangeHRM test -->
  </suite> <!-- OrangeHRM -->
</testng-results>
